version: '3.5'

services:
  mrsm-compose:
    build:
      context: "./"
      dockerfile: "./docker/Dockerfile"

    entrypoint: ["/app/docker/sleep_forever.sh"]

    environment: {}

    network_mode: "host"
    volumes:
      - "./:/app"
    init: true
    tty: true
    user: "meerschaum:meerschaum"
